receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# processors:
#   batch:
#     timeout: 10s
#     send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed

  otlphttp:
    endpoint: "http://apm-server:8200"  
    tls:
      insecure: true 

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch]
      exporters: [otlphttp,debug]
    metrics:
      receivers: [otlp]
      # processors: [batch]
      exporters: [otlphttp,debug]
    logs:
      receivers: [otlp]
      # processors: [batch]
      exporters: [otlphttp,debug]